# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - release/*
      - hotfix/*

pr:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: Gateway/paybyrd-deployment
      ref: refs/tags/1.13.1

variables:
  group: npm
  version_major: 1
  version_minor: 0
  version_patch: 0
 
stages:
- template: stages/prepare.yml@templates
- stage: build
  jobs:
  - job: build
    steps:
    #- bash: |
    #    sed -i "s/\"version\": \"1.0.0\",/\"version\": \"$VERSION\",/" package.json
    #  env:
    #    VERSION: $(Build.BuildNumber)
    #  name: updateVersion
    - bash: |
        npm install
      name: npmInstall
    - bash: |
        npm run build
      name: npmBuild
    - bash: |
        npm token create $TOKEN
      name: npmAccess
      env:
        TOKEN: $(NPM_API_TOKEN)
    - bash: |
        npm publish --public --tag $VERSION
      name: npmPublish
      env:
        VERSION: $(Build.Number)
      
      